// <auto-generated />
namespace BlogSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class onw1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onw1));
        
        string IMigrationMetadata.Id
        {
            get { return "201403012058138_onw1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
