// <auto-generated />
namespace BlogSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class onw38 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onw38));
        
        string IMigrationMetadata.Id
        {
            get { return "201403030658487_onw38"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
